language: objective-c
before_install:
    - brew update
    - brew unlink xctool
    - brew install xctool
script: xctool -project proj.ios_mac/rgb.xcodeproj -scheme rgb\ iOS -sdk iphonesimulator build test
